### ISSUE TITLE
InvalidIconSelectionException while trying to get an exe's icon by running a console application as a 64-bit process.

### ISSUE THREAD

**Issue by DevonTomatoSandwich** [pierresprim/IconLib#5]
If I install IconLib in a .NET Framework version: 4.7.2 project where the build setting "Prefer 32-bit" is false, I get an InvalidIconSelectionException when trying to extract icons from an exe using the below code.

```
using System;
using System.Drawing.IconLib;

namespace Test64bits472
{
    internal class main
    {
        static void Main()
        {
            try
            {
                var exePath = @"C:\path\to\aprogram.exe";
                string outFilePath = @"C:\Users\Admin\Desktop\test.png";

                var multiIcon = new MultiIcon();
                multiIcon.Load(exePath);
                Console.WriteLine($"Load finished");

                foreach (SingleIcon singleIcon in multiIcon)
                    Console.WriteLine($"singleIcon.Name = '{singleIcon.Name}'");

                multiIcon.Save(outFilePath, MultiIconFormat.ICO);
                Console.WriteLine($"Save finished");
            }
            catch (Exception e)
            {
                Console.WriteLine($"catch {e}");
            }
            finally
            {
                Console.WriteLine("finished");
                Console.ReadKey(); // Prevents screen from closing
            }
        }
    }
}

```

If running the code with the Save MultiIconFormat parameter as ICO, I get an InvalidIconSelectionException :
```
Load finished
catch System.Drawing.IconLib.Exceptions.InvalidIconSelectionException: Selected Icon is invalid
   at System.Drawing.IconLib.MultiIcon.Save(Stream stream, MultiIconFormat format)
   at System.Drawing.IconLib.MultiIcon.Save(String fileName, MultiIconFormat format)
   at Test64bits472.main.Main() in C:\<my redacted path>\Test64bits472\main.cs:line 22
finished
```

The png is produced but contains 0 bytes.

Looking at the source code, InvalidIconSelectionException is thrown for ICO format when mSelectedIndex == -1. I assume mSelectedIndex is related to the selected icon within the exe but since there are none (as my console logs do not show for printing each singleIcon Name) it would be set to -1. Setting the format to ICL will not throw an error but the singleIcon Name logs do not show either so no icons are found, a png is produduced with ICL format but it is 1kb and corrupted.

Switching the "Prefer 32-bit" to true works fine for ICO and ICL
**Why wont it work for 64bit?**

**Comment by DevonTomatoSandwich** [comment]
I solved this by implementing this SO solution

[https://stackoverflow.com/a/7940458/9713633](https://stackoverflow.com/a/7940458/9713633)

It involves using ExtractAssociatedIcon (which isn't always reliable) but when using it with IconLib and saving with the VistaFlag it somehow repairs the low-color image. This is working for me so far for extracting icons from 5 different exe applications

**Comment by DevonTomatoSandwich** [comment]
Marking as closed :)

**Comment by DevonTomatoSandwich** [comment]
Closing this :)
